local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>pg', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>g', builtin.live_grep, {})
vim.keymap.set("n", "<leader>g", ":lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>")
vim.keymap.set("n", "<leader>gw", "\"tyiw<CR>:lua require('telescope').extensions.live_grep_args.live_grep_args()<CR><C-r>t")
vim.keymap.set('n', '<leader>gr', builtin.lsp_references, {})
